version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
   
    commands:
        # install npm
        - yarn config set cache-folder /root/.yarn-cache
        - yarn install --frozen-lockfile
       
  build:
    commands:
        # run build script
        - npm run build
     
artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - '/root/.yarn-cache/**/*'
    - 'node_modules/**/*'